macro(CompilerFlags)
    if (MSVC)
        check_cxx_compiler_flag("/Qfast_transcendentals" FAST_TRANSCENDENTALS)
        if (FAST_TRANSCENDENTALS)
            list(APPEND GENERAL_COMPILE_OPTIONS "/Qfast_transcendentals")
        endif ()
        check_cxx_compiler_flag("/Ob3" AGGRESSIVE_INLINING)
        if (AGGRESSIVE_INLINING)
            list(APPEND GENERAL_COMPILE_OPTIONS "/Ob3")
        endif ()
        check_cxx_compiler_flag("/Oi" AGGRESSIVE_INTRINSIC)
        if (AGGRESSIVE_INTRINSIC)
            list(APPEND GENERAL_COMPILE_OPTIONS "/Oi")
        endif ()
        if (${CMAKE_SYSTEM_PROCESSOR} MATCHES "AMD64")
            check_cxx_compiler_flag("/arch:AVX" ARCH_AVX)
            if (ARCH_AVX)
                list(APPEND GENERAL_COMPILE_OPTIONS "/arch:AVX")
            endif ()
        elseif (${CMAKE_SYSTEM_PROCESSOR} MATCHES "ARM64")
            check_cxx_compiler_flag("/arch:armv8.2" ARCH_ARM82)
            if (ARCH_ARM82)
                list(APPEND GENERAL_COMPILE_OPTIONS "/arch:armv8.2")
            endif ()
        endif ()
    else ()
        check_cxx_compiler_flag("-funsafe-math-optimizations" UNSAFE_MATH)
        if (UNSAFE_MATH)
            list(APPEND GENERAL_COMPILE_OPTIONS "-funsafe-math-optimizations")
        endif ()
        check_cxx_compiler_flag("-fno-trapping-math" TRAPPING_MATH)
        if (TRAPPING_MATH)
            list(APPEND GENERAL_COMPILE_OPTIONS "-fno-trapping-math")
        endif ()
        check_cxx_compiler_flag("-fno-math-errno" ERRNO_MATH)
        if (ERRNO_MATH)
            list(APPEND GENERAL_COMPILE_OPTIONS "-fno-math-errno")
        endif ()
        check_cxx_compiler_flag("-fno-signed-zeros" UNSIGNED_ZERO)
        if (UNSIGNED_ZERO)
            list(APPEND GENERAL_COMPILE_OPTIONS "-fno-signed-zeros")
        endif ()
        check_cxx_compiler_flag("-freciprocal-math" RECIPROCAL_MATH)
        if (RECIPROCAL_MATH)
            list(APPEND GENERAL_COMPILE_OPTIONS "-freciprocal-math")
        endif ()
        if (${CMAKE_SYSTEM_PROCESSOR} MATCHES "x86_64" OR ${CMAKE_SYSTEM_PROCESSOR} MATCHES "AMD64")
            check_cxx_compiler_flag("-mavx" ARCH_AVX)
            if (ARCH_AVX)
                list(APPEND GENERAL_COMPILE_OPTIONS "-mavx")
            endif ()
            check_cxx_compiler_flag("-mpopcnt" HAS_POPCNT)
            if (HAS_POPCNT)
                list(APPEND GENERAL_COMPILE_OPTIONS "-mpopcnt")
            endif ()
        endif ()
        if (${CMAKE_SYSTEM_PROCESSOR} MATCHES "aarch64" OR ${CMAKE_SYSTEM_PROCESSOR} MATCHES "ARM64")
            check_cxx_compiler_flag("-march=armv8.2-a+simd" ARCH_ARM82)
            if (ARCH_ARM82)
                list(APPEND GENERAL_COMPILE_OPTIONS "-march=armv8.2-a+simd")
            endif ()
        endif ()
    endif ()
endmacro()