macro(DetectOMP)
    if (NOT (APPLE AND (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES arm64)) AND NOT (BUILD_RCPP AND NOT BUILD_SHARED_LIBS))
        find_package(OpenMP)
        if (OpenMP_CXX_FOUND)
            if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND NOT APPLE)
            list(APPEND GENERAL_COMPILE_OPTIONS "/clang:-fopenmp")
            list(APPEND GENERAL_LINK_OPTIONS "libomp.lib")
            elseif (MSVC)
                set(OpenMP_CXX_FLAGS "-openmp:llvm")
            endif ()
            list(APPEND GENERAL_COMPILE_OPTIONS ${OpenMP_CXX_FLAGS})
            #list(APPEND GENERAL_LINK_OPTIONS ${OpenMP_CXX_FLAGS})
        endif ()
    endif ()
endmacro()