macro(RcppDefines)
    include(FindRModule)
    if (APPLE)
        set(CMAKE_PROGRAM_PATH /opt/R/${CMAKE_HOST_SYSTEM_PROCESSOR}/bin)
        set(CMAKE_LIBRARY_PATH /opt/R/${CMAKE_HOST_SYSTEM_PROCESSOR}/lib)
        set(CMAKE_INCLUDE_PATH /opt/R/${CMAKE_HOST_SYSTEM_PROCESSOR}/include)
    endif ()
    find_package(R REQUIRED)
    list(APPEND GENERAL_DEFINES USING_R)
    if (NOT BUILD_SHARED_LIBS)
        list(APPEND GENERAL_COMPILE_OPTIONS ${R_OPENMP_CXXFLAGS})
        list(APPEND GENERAL_LINK_OPTIONS ${R_OPENMP_CXXFLAGS})
    elseif (OpenMP_CXX_FOUND)
        set(MKL_THREADING gnu_thread)
    else ()
        set(MKL_THREADING sequential)
    endif ()
    set(MKL_INTERFACE lp64)
    if (R_RHOME MATCHES "^/data/gannet/ripley/R/.*")
        set(BLA_VENDOR Generic)
    endif ()
    find_r_module(Rcpp)
    find_r_module(RcppArmadillo)
    find_r_module(RcppProgress)
    if (R_INCLUDE_DIR)
        list(APPEND GENERAL_INCLUDE_DIRS "${R_INCLUDE_DIR}")
    else ()
        message(FATAL_ERROR "missing R headers")
    endif ()
    if (R_RCPP)
        list(APPEND GENERAL_INCLUDE_DIRS "${R_RCPP}/include")
    else ()
        message(FATAL_ERROR "missing RcppArmadillo")
    endif ()
    if (R_RCPPARMADILLO)
        list(APPEND GENERAL_INCLUDE_DIRS "${R_RCPPARMADILLO}/include")
    else ()
        message(FATAL_ERROR "missing RcppArmadillo")
    endif ()
    if (R_RCPPPROGRESS)
        list(APPEND GENERAL_INCLUDE_DIRS "${R_RCPPPROGRESS}/include")
    else ()
        message(FATAL_ERROR "missing RcppProgress")
    endif ()
endmacro()